
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEASSIGN DIVIDE LPAREN MINUS NAME NUMBER PLUS PRINT RPAREN SEMICOLON TIMESstart : blocbloc : bloc statement SEMICOLON\n| statement SEMICOLONstatement : NAME ASSIGN expressionstatement : PRINT LPAREN expression RPARENexpression : expression PLUS expressionexpression : expression MINUS expressionexpression : expression TIMES expressionexpression : expression DIVIDE expressionexpression : LPAREN expression RPARENexpression : NUMBERexpression : NAME'
    
_lr_action_items = {'NAME':([0,2,7,8,9,10,13,16,17,18,19,],[4,4,-3,11,11,-2,11,11,11,11,11,]),'PRINT':([0,2,7,10,],[5,5,-3,-2,]),'$end':([1,2,7,10,],[0,-1,-3,-2,]),'SEMICOLON':([3,6,11,12,14,21,22,23,24,25,26,],[7,10,-12,-4,-11,-5,-6,-7,-8,-9,-10,]),'ASSIGN':([4,],[8,]),'LPAREN':([5,8,9,13,16,17,18,19,],[9,13,13,13,13,13,13,13,]),'NUMBER':([8,9,13,16,17,18,19,],[14,14,14,14,14,14,14,]),'PLUS':([11,12,14,15,20,22,23,24,25,26,],[-12,16,-11,16,16,-6,-7,-8,-9,-10,]),'MINUS':([11,12,14,15,20,22,23,24,25,26,],[-12,17,-11,17,17,-6,-7,-8,-9,-10,]),'TIMES':([11,12,14,15,20,22,23,24,25,26,],[-12,18,-11,18,18,18,18,-8,-9,-10,]),'DIVIDE':([11,12,14,15,20,22,23,24,25,26,],[-12,19,-11,19,19,19,19,-8,-9,-10,]),'RPAREN':([11,14,15,20,22,23,24,25,26,],[-12,-11,21,26,-6,-7,-8,-9,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'bloc':([0,],[2,]),'statement':([0,2,],[3,6,]),'expression':([8,9,13,16,17,18,19,],[12,15,20,22,23,24,25,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> bloc','start',1,'p_start','main.py',57),
  ('bloc -> bloc statement SEMICOLON','bloc',3,'p_bloc','main.py',61),
  ('bloc -> statement SEMICOLON','bloc',2,'p_bloc','main.py',62),
  ('statement -> NAME ASSIGN expression','statement',3,'p_statement_assign','main.py',69),
  ('statement -> PRINT LPAREN expression RPAREN','statement',4,'p_statement_print','main.py',73),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop_plus','main.py',77),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop_minus','main.py',81),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop_times','main.py',85),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop_divide','main.py',89),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','main.py',93),
  ('expression -> NUMBER','expression',1,'p_expression_number','main.py',97),
  ('expression -> NAME','expression',1,'p_expression_var','main.py',101),
]
